# QCC Production Configuration
# This file contains configuration settings for the QCC production environment

# Assembler Configuration
assembler:
  host: 0.0.0.0
  port: 443
  development_mode: false
  log_level: info
  
  # Resource limits for the assembler process
  resources:
    max_memory_mb: 1024
    max_cpu_percent: 70
    
  # Security settings for production
  security:
    verification_mode: strict  # Options: standard, strict
    allow_unverified_cells: false
    require_https: true
    authentication_required: true
    auth_service_url: https://auth.cellcomputing.ai/v1
    
  # Performance settings
  performance:
    prefetch_enabled: true
    prefetch_threshold: 0.85
    cell_cache_size_mb: 512
    max_concurrent_assemblies: 50
    
  # Intent interpretation settings
  intent:
    confidence_threshold: 0.75
    fallback_capability: text_generation
    context_window_size: 20
    max_intent_complexity: 10

# Provider Configuration
providers:
  - name: primary_provider
    url: https://provider-primary.cellcomputing.ai
    priority: 1
    capabilities:
      - text_generation
      - file_system
      - ui_rendering
      - data_visualization
      - network_interface
      - media_player
      - text_editor
      - calculator
      - image_processing
    auth:
      api_key_env: PRIMARY_PROVIDER_API_KEY
    rate_limiting:
      max_requests_per_second: 100
      max_requests_per_minute: 2000
    
  - name: backup_provider
    url: https://provider-backup.cellcomputing.ai
    priority: 2
    capabilities:
      - text_generation
      - file_system
      - ui_rendering
      - data_visualization
      - network_interface
    auth:
      api_key_env: BACKUP_PROVIDER_API_KEY
    rate_limiting:
      max_requests_per_second: 50
      max_requests_per_minute: 1000

  - name: specialized_provider
    url: https://provider-specialized.cellcomputing.ai
    priority: 3
    capabilities:
      - advanced_image_processing
      - scientific_computing
      - medical_diagnostics
    auth:
      api_key_env: SPECIALIZED_PROVIDER_API_KEY
    rate_limiting:
      max_requests_per_second: 20
      max_requests_per_minute: 500

# Quantum Trail Configuration
quantum_trail:
  enabled: true
  local_blockchain: false
  sync_interval_ms: 10000
  
  # Production blockchain settings
  blockchain:
    consensus: proof_of_stake
    nodes:
      - https://blockchain-node1.cellcomputing.ai
      - https://blockchain-node2.cellcomputing.ai
      - https://blockchain-node3.cellcomputing.ai
    max_transaction_size_kb: 128
    
  # Trail settings
  trail:
    anonymization_level: enhanced  # Options: basic, standard, enhanced
    pattern_recognition_enabled: true
    max_trail_history_days: 90
    encryption_enabled: true
    pruning_interval_days: 7

# Cell Runtime Settings
cells:
  # Cell runtime settings
  runtime:
    execution_timeout_ms: 30000
    max_memory_per_cell_mb: 256
    max_concurrent_cells: 100
    resource_monitoring_interval_ms: 1000
    
  # Cell verification settings
  verification:
    signature_verification: true
    code_scanning_enabled: true
    behavior_analysis_enabled: true
    vulnerability_checking: true

# Logging Configuration
logging:
  file_path: /var/log/qcc/production.log
  log_rotation:
    enabled: true
    max_size_mb: 100
    backup_count: 10
  console_level: warning
  file_level: info
  format: json  # Options: simple, detailed, json
  components:
    assembler: info
    cells: info
    providers: info
    quantum_trail: info
    runtime: info
    security: info

# Monitoring and Alerting
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  prometheus_endpoint: /metrics
  health_check_interval_seconds: 60
  alerting:
    enabled: true
    email_alerts: ops@cellcomputing.ai
    sms_alerts: true
    sms_phone_numbers_env: ALERT_PHONE_NUMBERS
    pagerduty_integration_key_env: PAGERDUTY_KEY

# Networking
network:
  cors_enabled: false
  allowed_origins:
    - https://app.cellcomputing.ai
    - https://api.cellcomputing.ai
  request_timeout_ms: 60000
  max_payload_size_mb: 50
  tls:
    cert_path: /etc/qcc/ssl/cert.pem
    key_path: /etc/qcc/ssl/key.pem
    min_version: TLS1.2
  rate_limiting:
    enabled: true
    requests_per_minute: 300
    burst: 50

# Storage
storage:
  data_directory: /var/lib/qcc/data
  temp_directory: /var/lib/qcc/temp
  max_storage_gb: 100
  auto_cleanup_enabled: true
  retention_days: 30
  
  # Cache settings
  cache:
    enable_filesystem_cache: true
    cache_directory: /var/cache/qcc
    max_cache_size_mb: 4096
    ttl_seconds: 86400  # 24 hours
    distributed_cache:
      enabled: true
      redis_url_env: REDIS_URL

# Fault Tolerance
fault_tolerance:
  max_retries: 3
  retry_delay_ms: 1000
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    reset_timeout_ms: 30000
  graceful_degradation:
    enabled: true
    essential_capabilities:
      - file_system
      - text_generation
      - ui_rendering

# Production-specific features
features:
  telemetry_enabled: true
  usage_analytics_enabled: true
  auto_scaling_enabled: true
  performance_optimization_level: high
  cell_update_notification: true
  
# Deployment
deployment:
  environment: production
  region: us-west
  container_orchestration: kubernetes
  health_endpoint: /health
  readiness_endpoint: /ready
  liveness_endpoint: /alive
  startup_timeout_seconds: 60
